"""
BetFred CV Service Utils Module
Provides utility functions and configuration for the CV service
"""
from .config import *

__all__ = [
    'ALL_WRITERS', 'WRITER_TO_ID', 'ID_TO_WRITER', 'DEMO_WRITERS',
    'DEMO_WRITER_TO_ID', 'DEMO_ID_TO_WRITER', 'DEMO_FILE_MAPPING',
    'DEMO_MODE', 'DEMO_CONFIDENCE_BASE', 'DEMO_HIGH_CONFIDENCE',
    'DEMO_MEDIUM_CONFIDENCE', 'BATCH_SIZE', 'LEARNING_RATE',
    'NUM_EPOCHS', 'IMAGE_SIZE', 'DROPOUT_RATE', 'SLIPS_DIR',
    'MODEL_SAVE_PATH', 'BEST_MODEL_NAME', 'DEMO_OUTPUTS_DIR',
    'HIGH_CONFIDENCE_THRESHOLD', 'MEDIUM_CONFIDENCE_THRESHOLD',
    'MIN_ACCURACY_THRESHOLD'
]
